services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api-server
    ports:
      - 3300:80
    command: ["nginx", "-g", "daemon off;"]

  api-server:
    image: lorddickson/api-server:latest
    ports:
      - "8081:8081"
    volumes:
      - ./api-server:/src
      - ~/.aws:/root/.aws:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    command: ["/app/api"]

  ai-service:
    image: lorddickson/ai-service:slim
    ports:
      - "50052:50052"
    volumes:
      - /app/venv
      - ai-model-cache:/root/.cache/huggingface
    environment:
      # Add any required environment variables
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
    command: ["/opt/venv/bin/python", "main.py"]

  cenphidb:
    image: postgres:latest
    container_name: cenphi_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "cenphidb"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql

volumes:
  dbdata:
    name: cenphi_dbdata
  ai-model-cache:
    name: cenphi_ai_models
