import { Brain, RefreshCw, Share, Sparkles, Target, Zap } from "lucide-react";
import { Testimonial } from "./types";

export const testimonials: Testimonial[] = [
  {
    id: 1,
    text: "The AI-powered testimonial optimization completely transformed how we showcase customer success. Our conversion rates increased by 312% within just 2 months.",
    author: "Sarah Chen",
    role: "Head of Growth",
    company: "TechForward Inc.",
    category: "enterprise",
    rating: 5,
    metrics: {
      conversionLift: "+312%",
      testimonialEngagement: "8.4x",
      brandTrust: "97%",
      roi: "22.5x",
      customerSatisfaction: "95%",
      referralRate: "12%",
    },
    keywords: ["AI-Powered", "Enterprise-Grade", "Conversion-Focused"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Destiny",
    verification: {
      verified: true,
      platform: "LinkedIn",
      date: "2024-02-15",
    },
  },
  {
    id: 2,
    text: "Implementing the AI testimonial tool skyrocketed our lead generation. Within 3 months, our engagement jumped by 210%.",
    author: "Mark Johnson",
    role: "CMO",
    company: "Innovatech Solutions",
    category: "saas",
    rating: 5,
    metrics: {
      conversionLift: "+210%",
      testimonialEngagement: "7.5x",
      brandTrust: "95%",
      roi: "18.0x",
      customerSatisfaction: "93%",
      referralRate: "10%",
    },
    keywords: ["AI-Driven", "Innovative", "Lead Generation"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Vision",
    verification: {
      verified: true,
      platform: "Twitter",
      date: "2024-03-01",
    },
  },
  {
    id: 3,
    text: "Our marketing team saw a dramatic improvement in user trust after integrating testimonial analytics. Engagement increased by over 150%.",
    author: "Alice Nguyen",
    role: "Marketing Director",
    company: "Creative Minds",
    category: "startup",
    rating: 4.5,
    metrics: {
      conversionLift: "+150%",
      testimonialEngagement: "6.2x",
      brandTrust: "93%",
      roi: "15.0x",
      customerSatisfaction: "90%",
      referralRate: "8%",
    },
    keywords: ["Analytics", "User Trust", "Creative"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Inspire",
    verification: {
      verified: true,
      platform: "LinkedIn",
      date: "2024-01-20",
    },
  },
  {
    id: 4,
    text: "The testimonial optimization tool is a game-changer. It refined our brand message and doubled our ROI within weeks.",
    author: "David Kim",
    role: "VP of Marketing",
    company: "BrandBuilders",
    category: "enterprise",
    rating: 5,
    metrics: {
      conversionLift: "+200%",
      testimonialEngagement: "8.0x",
      brandTrust: "96%",
      roi: "20.0x",
      customerSatisfaction: "94%",
      referralRate: "11%",
    },
    keywords: ["Optimization", "Brand Message", "ROI"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Legacy",
    verification: {
      verified: true,
      platform: "LinkedIn",
      date: "2024-02-10",
    },
  },
  {
    id: 5,
    text: "This tool has redefined our testimonial strategy. Engagement metrics have never been higher, and our brand trust is through the roof.",
    author: "Emma Rodriguez",
    role: "Chief Strategy Officer",
    company: "Visionary Ventures",
    category: "startup",
    rating: 4.8,
    metrics: {
      conversionLift: "+275%",
      testimonialEngagement: "7.8x",
      brandTrust: "98%",
      roi: "25.5x",
      customerSatisfaction: "97%",
      referralRate: "13%",
    },
    keywords: ["Strategy", "Engagement", "Trust"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Momentum",
    verification: {
      verified: true,
      platform: "LinkedIn",
      date: "2024-03-05",
    },
  },
  {
    id: 6,
    text: "Integrating advanced testimonial insights helped us fine-tune our messaging. Our customer satisfaction and conversion rates soared.",
    author: "Oliver Smith",
    role: "Product Manager",
    company: "NextGen Apps",
    category: "enterprise",
    rating: 4.7,
    metrics: {
      conversionLift: "+180%",
      testimonialEngagement: "7.0x",
      brandTrust: "92%",
      roi: "16.5x",
      customerSatisfaction: "91%",
      referralRate: "9%",
    },
    keywords: ["Insights", "Messaging", "Customer Success"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Momentum2",
    verification: {
      verified: false,
      platform: "Facebook",
      date: "2024-01-30",
    },
  },
  {
    id: 7,
    text: "The testimonial tool streamlined our review process and provided actionable insights that drove a 190% increase in conversion.",
    author: "Sophia Li",
    role: "Customer Success Lead",
    company: "ServiceFirst",
    category: "startup",
    rating: 5,
    metrics: {
      conversionLift: "+190%",
      testimonialEngagement: "8.2x",
      brandTrust: "94%",
      roi: "19.5x",
      customerSatisfaction: "96%",
      referralRate: "10%",
    },
    keywords: ["Streamlined", "Actionable Insights", "Conversion"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Serenity",
    verification: {
      verified: true,
      platform: "LinkedIn",
      date: "2024-02-28",
    },
  },
  {
    id: 8,
    text: "Our testimonial engagement has been revitalized thanks to the precision targeting offered by this AI-powered solution.",
    author: "Liam Patel",
    role: "Digital Marketing Manager",
    company: "AdVantage Media",
    category: "saas",
    rating: 4.9,
    metrics: {
      conversionLift: "+230%",
      testimonialEngagement: "8.6x",
      brandTrust: "97%",
      roi: "21.0x",
      customerSatisfaction: "95%",
      referralRate: "12%",
    },
    keywords: ["Precision Targeting", "Digital Marketing", "AI-Powered"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Momentum3",
    verification: {
      verified: false,
      platform: "Twitter",
      date: "2024-03-10",
    },
  },
  {
    id: 9,
    text: "The transformation in our customer testimonials has been extraordinary. This tool has allowed us to scale our impact effectively.",
    author: "Mia Brown",
    role: "CMO",
    company: "ScaleUp Inc.",
    category: "enterprise",
    rating: 5,
    metrics: {
      conversionLift: "+320%",
      testimonialEngagement: "9.0x",
      brandTrust: "99%",
      roi: "26.0x",
      customerSatisfaction: "98%",
      referralRate: "14%",
    },
    keywords: ["Transformation", "Scaling", "Impact"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Momentum4",
    verification: {
      verified: true,
      platform: "LinkedIn",
      date: "2024-02-05",
    },
  },
  {
    id: 10,
    text: "Our revenue growth skyrocketed after incorporating these optimized testimonials into our campaign strategy. It’s a true game-changer.",
    author: "Ethan Davis",
    role: "Head of Sales",
    company: "ProfitBoost",
    category: "saas",
    rating: 5,
    metrics: {
      conversionLift: "+290%",
      testimonialEngagement: "8.5x",
      brandTrust: "96%",
      roi: "23.0x",
      customerSatisfaction: "94%",
      referralRate: "11%",
    },
    keywords: ["Revenue Growth", "Game-Changer", "Optimized Testimonials"],
    image: "https://api.dicebear.com/9.x/notionists/svg?seed=Momentum5",
    verification: {
      verified: true,
      platform: "LinkedIn",
      date: "2024-03-15",
    },
  },
];

export const features = [
  {
    icon: Brain,
    title: "AI-Powered Enhancement",
    description:
      "Automatically optimize testimonials for maximum impact and relevance",
  },
  {
    icon: RefreshCw,
    title: "Smart Curation",
    description:
      "Intelligently organize and display your most impactful customer stories",
  },
  {
    icon: Share,
    title: "Dynamic Distribution",
    description:
      "Share testimonials across all channels with perfect formatting",
  },
  {
    icon: Sparkles,
    title: "Premium Analytics",
    description: "Deep insights into testimonial performance and engagement",
  },
  {
    icon: Target,
    title: "Audience Targeting",
    description: "Show the right testimonials to the right audience segments",
  },
  {
    icon: Zap,
    title: "Instant Impact",
    description: "Real-time optimization for maximum conversion rates",
  },
];
