import {
  DiscoveryMode,
  PlatformAccount,
  PlatformColors,
  PlatformDevUrls,
  PlatformIcons,
  PlatformNames,
  PlatformPermissions,
  SocialPlatformName,
} from "@/types/setup";
import { Testimonial } from "@/types/testimonial";
import {
  Instagram,
  Twitter,
  Facebook,
  Linkedin,
  Youtube,
  Command,
  User,
  MessageSquare,
  BarChart,
  Eye,
  PencilRuler,
  Lock,
  Upload,
  HeartHandshake,
  Users,
  UserPlus,
  Share,
  Zap,
  Search,
  Heart,
  Sparkles,
} from "lucide-react";

export const platformDevUrls: PlatformDevUrls = {
  instagram: "https://developers.facebook.com/docs/instagram-api/",
  twitter: "https://developer.twitter.com/en/docs/twitter-api",
  facebook: "https://developers.facebook.com/docs/",
  linkedin: "https://developer.linkedin.com/",
  tiktok: "https://developers.tiktok.com/",
  youtube: "https://developers.google.com/youtube/",
};

// Platform colors
export const platformColors: PlatformColors = {
  instagram: {
    bg: "bg-gradient-to-tr from-amber-500 via-pink-500 to-purple-600",
    text: "text-white",
    border: "border-pink-300",
    gradientFrom: "from-amber-500",
    gradientTo: "to-purple-600",
    hoverFrom: "hover:from-amber-600",
    hoverTo: "hover:to-purple-700",
    lightBg: "bg-pink-50",
  },
  twitter: {
    bg: "bg-sky-500",
    text: "text-white",
    border: "border-sky-300",
    gradientFrom: "from-sky-500",
    gradientTo: "to-blue-500",
    hoverFrom: "hover:from-sky-600",
    hoverTo: "hover:to-blue-600",
    lightBg: "bg-sky-50",
  },
  facebook: {
    bg: "bg-blue-600",
    text: "text-white",
    border: "border-blue-300",
    gradientFrom: "from-blue-600",
    gradientTo: "to-blue-700",
    hoverFrom: "hover:from-blue-700",
    hoverTo: "hover:to-blue-800",
    lightBg: "bg-blue-50",
  },
  linkedin: {
    bg: "bg-blue-700",
    text: "text-white",
    border: "border-blue-400",
    gradientFrom: "from-blue-700",
    gradientTo: "to-blue-800",
    hoverFrom: "hover:from-blue-800",
    hoverTo: "hover:to-blue-900",
    lightBg: "bg-blue-50",
  },
  tiktok: {
    bg: "bg-black",
    text: "text-white",
    border: "border-gray-500",
    gradientFrom: "from-gray-900",
    gradientTo: "to-black",
    hoverFrom: "hover:from-gray-800",
    hoverTo: "hover:to-black",
    lightBg: "bg-slate-50",
  },
  youtube: {
    bg: "bg-red-600",
    text: "text-white",
    border: "border-red-300",
    gradientFrom: "from-red-600",
    gradientTo: "to-red-700",
    hoverFrom: "hover:from-red-700",
    hoverTo: "hover:to-red-800",
    lightBg: "bg-red-50",
  },
};

// Platform-specific permission requirements
export const platformPermissions: PlatformPermissions = {
  instagram: [
    {
      id: "instagram_basic",
      name: "Instagram Basic Display API",
      description: "Access to profile information and media",
      required: true,
      icon: User,
    },
    {
      id: "instagram_content_publish",
      name: "Content Publishing",
      description: "Ability to publish content and respond to comments",
      required: false,
      icon: Share,
    },
    {
      id: "instagram_manage",
      name: "Instagram Manage",
      description: "Manage comments and insights",
      required: true,
      icon: MessageSquare,
    },
    {
      id: "instagram_manage_insights",
      name: "Manage Insights",
      description: "Access to post and account insights",
      required: false,
      icon: BarChart,
    },
  ],
  facebook: [
    {
      id: "pages_read_engagement",
      name: "Pages Read Engagement",
      description: "Read content and engagement on your Facebook pages",
      required: true,
      icon: Eye,
    },
    {
      id: "pages_manage_posts",
      name: "Pages Manage Posts",
      description: "Create and manage posts as a Facebook page",
      required: false,
      icon: PencilRuler,
    },
    {
      id: "pages_messaging",
      name: "Pages Messaging",
      description: "Send and receive messages as a Facebook page",
      required: true,
      icon: MessageSquare,
    },
    {
      id: "pages_show_list",
      name: "Pages Show List",
      description: "Access list of Facebook pages you manage",
      required: true,
      icon: Users,
    },
  ],
  twitter: [
    {
      id: "tweet.read",
      name: "Tweet Read",
      description: "Read Tweets from your timeline",
      required: true,
      icon: Eye,
    },
    {
      id: "users.read",
      name: "Users Read",
      description: "Read user profile information",
      required: true,
      icon: User,
    },
    {
      id: "follows.read",
      name: "Follows Read",
      description: "See who follows you and who you follow",
      required: false,
      icon: Users,
    },
    {
      id: "follows.write",
      name: "Follows Write",
      description: "Follow and unfollow accounts for you",
      required: false,
      icon: UserPlus,
    },
  ],
  linkedin: [
    {
      id: "r_basicprofile",
      name: "Basic Profile",
      description: "Read your basic profile info",
      required: true,
      icon: User,
    },
    {
      id: "r_organization_social",
      name: "Organization Social",
      description: "Access to company pages you manage",
      required: true,
      icon: Users,
    },
    {
      id: "w_organization_social",
      name: "Organization Social Write",
      description: "Update company pages you manage",
      required: false,
      icon: PencilRuler,
    },
    {
      id: "r_member_social",
      name: "Member Social",
      description: "Access to your posts, comments, and reactions",
      required: true,
      icon: MessageSquare,
    },
  ],
  youtube: [
    {
      id: "youtube.readonly",
      name: "YouTube Read Only",
      description: "View your YouTube channel information",
      required: true,
      icon: Eye,
    },
    {
      id: "youtube.force-ssl",
      name: "Force SSL",
      description: "HTTPS connection required for security",
      required: true,
      icon: Lock,
    },
    {
      id: "youtube.upload",
      name: "YouTube Upload",
      description: "Upload videos to your YouTube channel",
      required: false,
      icon: Upload,
    },
    {
      id: "youtube.channel-memberships.creator",
      name: "Channel Memberships",
      description: "View your channel membership details",
      required: false,
      icon: HeartHandshake,
    },
  ],
  tiktok: [
    {
      id: "user.info.basic",
      name: "User Basic Info",
      description: "Access to basic profile information",
      required: true,
      icon: User,
    },
    {
      id: "video.list",
      name: "Video List",
      description: "List videos from your TikTok account",
      required: true,
      icon: Eye,
    },
    {
      id: "video.upload",
      name: "Video Upload",
      description: "Upload videos to your TikTok account",
      required: false,
      icon: Upload,
    },
    {
      id: "comment.list",
      name: "Comment List",
      description: "Read comments on your videos",
      required: true,
      icon: MessageSquare,
    },
  ],
};

// Platform icons mapping
export const platformIcons: PlatformIcons = {
  instagram: Instagram,
  twitter: Twitter,
  facebook: Facebook,
  linkedin: Linkedin,
  tiktok: Command,
  youtube: Youtube,
};

// Platform display names
export const platformNames: PlatformNames = {
  instagram: "Instagram",
  twitter: "Twitter / X",
  facebook: "Facebook",
  linkedin: "LinkedIn",
  tiktok: "TikTok",
  youtube: "YouTube",
};

// Get mock accounts for a platform
export const getMockAccounts = (
  platform: SocialPlatformName
): PlatformAccount[] => {
  switch (platform) {
    case "facebook":
      return [
        {
          id: "fb1",
          name: "Your Business Page",
          username: "yourbusinesspage",
          type: "business",
          followers: 1250,
          verified: true,
        },
        {
          id: "fb2",
          name: "Your Personal Profile",
          username: "yourname",
          type: "personal",
          followers: 520,
          verified: false,
        },
      ];
    case "instagram":
      return [
        {
          id: "ig1",
          name: "Your Brand",
          username: "yourbrand",
          type: "business",
          followers: 3420,
          verified: true,
        },
        {
          id: "ig2",
          name: "Your Secondary Account",
          username: "yourbrand.secondary",
          type: "business",
          followers: 980,
          verified: false,
        },
      ];
    case "twitter":
      return [
        {
          id: "tw1",
          name: "Your Company",
          username: "yourcompany",
          type: "business",
          followers: 2150,
          verified: true,
        },
        {
          id: "tw2",
          name: "Your Product",
          username: "yourproduct",
          type: "business",
          followers: 870,
          verified: false,
        },
      ];
    case "linkedin":
      return [
        {
          id: "li1",
          name: "Your Company Page",
          username: "your-company",
          type: "business",
          followers: 1590,
          verified: true,
        },
        {
          id: "li2",
          name: "Your Personal Profile",
          username: "your.name",
          type: "personal",
          followers: 750,
          verified: false,
        },
      ];
    case "youtube":
      return [
        {
          id: "yt1",
          name: "Your Channel",
          username: "YourChannel",
          type: "creator",
          followers: 5200,
          verified: true,
        },
        {
          id: "yt2",
          name: "Your Brand Channel",
          username: "YourBrandOfficial",
          type: "business",
          followers: 2800,
          verified: true,
        },
      ];
    case "tiktok":
      return [
        {
          id: "tt1",
          name: "Your TikTok",
          username: "@yourbrand",
          type: "business",
          followers: 6800,
          verified: false,
        },
        {
          id: "tt2",
          name: "Your Creator Account",
          username: "@yourcreator",
          type: "creator",
          followers: 12400,
          verified: true,
        },
      ];
    default:
      return [
        {
          id: `${platform}1`,
          name: "Your Account",
          username: "youraccount",
          type: "business",
          followers: 1000,
          verified: false,
        },
      ];
  }
};

export const mockTestimonials: Testimonial[] = [
  {
    id: "t1",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "pending", // mapped from original "pending"
    content:
      "I've been using @brandname for the past 3 months and it has completely transformed how I organize my projects. The intuitive interface and powerful features are exactly what I've been looking for!",
    rating: 5,
    collection_method: "social_import",
    verification_status: "unverified",
    published: false,
    tags: ["productivity", "software", "organization"],
    view_count: 0,
    share_count: 12,
    conversion_count: 0,
    engagement_metrics: { likes: 28, comments: 5, shares: 12 },
    created_at: new Date("2023-10-15T14:30:00Z"),
    updated_at: new Date("2023-10-15T14:30:00Z"),
    customer_profile: {
      id: "c1",
      workspace_id: "workspace_1",
      name: "Sarah Johnson",
      avatar_url: "https://randomuser.me/api/portraits/women/32.jpg",
      social_profiles: {
        username: "sarahj",
        platform: "twitter",
        verified: true,
        followers: 2543,
      },
      created_at: new Date("2023-10-15T14:30:00Z"),
      updated_at: new Date("2023-10-15T14:30:00Z"),
    },
    source_data: {
      platform: "twitter",
      source: "mentions",
      sentiment: "positive",
      score: 0.92,
    },
    custom_fields: {},
  },
  {
    id: "t2",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "approved",
    content:
      "Never thought I'd find a solution that actually works for me, but @brandname exceeded all my expectations. Their customer service is top-notch too! #HappyCustomer",
    collection_method: "social_import",
    verification_status: "unverified",
    published: true,
    tags: ["customer service", "expectations"],
    media_urls: [
      "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    ],
    view_count: 0,
    share_count: 0,
    conversion_count: 0,
    engagement_metrics: { likes: 142, comments: 17 },
    created_at: new Date("2023-10-12T09:15:00Z"),
    updated_at: new Date("2023-10-12T09:15:00Z"),
    customer_profile: {
      id: "c2",
      workspace_id: "workspace_1",
      name: "Mark Chen",
      avatar_url: "https://randomuser.me/api/portraits/men/45.jpg",
      social_profiles: {
        username: "mark_explores",
        platform: "instagram",
        followers: 5231,
      },
      created_at: new Date("2023-10-12T09:15:00Z"),
      updated_at: new Date("2023-10-12T09:15:00Z"),
    },
    source_data: {
      platform: "instagram",
      source: "tags",
      sentiment: "positive",
      score: 0.87,
    },
    custom_fields: {},
  },
  {
    id: "t3",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "approved",
    content:
      "I was skeptical at first but decided to give it a try. So glad I did! This tool has saved me countless hours every week. Definitely worth the investment.",
    rating: 4,
    collection_method: "social_import",
    verification_status: "unverified",
    published: true,
    tags: ["time-saving", "ROI", "productivity"],
    view_count: 0,
    share_count: 0,
    conversion_count: 0,
    engagement_metrics: { likes: 38, comments: 3 },
    created_at: new Date("2023-10-08T16:45:00Z"),
    updated_at: new Date("2023-10-08T16:45:00Z"),
    customer_profile: {
      id: "c3",
      workspace_id: "workspace_1",
      name: "Jennifer Smith",
      avatar_url: "https://randomuser.me/api/portraits/women/22.jpg",
      social_profiles: { username: "jensmith", platform: "facebook" },
      created_at: new Date("2023-10-08T16:45:00Z"),
      updated_at: new Date("2023-10-08T16:45:00Z"),
    },
    source_data: {
      platform: "facebook",
      source: "comments",
      sentiment: "positive",
      score: 0.79,
    },
    custom_fields: {},
  },
  {
    id: "t4",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "pending",
    content:
      "Been testing several similar products for our company and this one stands out by far. The team behind it really understands what professionals need. Highly recommend for any business looking to streamline their processes.",
    collection_method: "social_import",
    verification_status: "unverified",
    published: false,
    tags: ["business", "professional", "streamline"],
    view_count: 0,
    share_count: 9,
    conversion_count: 0,
    engagement_metrics: { likes: 86, comments: 12, shares: 9 },
    created_at: new Date("2023-10-05T10:20:00Z"),
    updated_at: new Date("2023-10-05T10:20:00Z"),
    customer_profile: {
      id: "c4",
      workspace_id: "workspace_1",
      name: "Michael Torres",
      avatar_url: "https://randomuser.me/api/portraits/men/22.jpg",
      social_profiles: {
        username: "michael.torres",
        platform: "linkedin",
        followers: 1832,
      },
      created_at: new Date("2023-10-05T10:20:00Z"),
      updated_at: new Date("2023-10-05T10:20:00Z"),
    },
    source_data: {
      platform: "linkedin",
      source: "posts",
      sentiment: "positive",
      score: 0.94,
    },
    custom_fields: {},
  },
  {
    id: "t5",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "rejected",
    content:
      "Having some issues with the latest update. The new interface is confusing and I can't find features that I used daily. @brandname please fix this!",
    collection_method: "social_import",
    verification_status: "unverified",
    published: false,
    tags: ["bugs", "user interface", "update"],
    view_count: 0,
    share_count: 0,
    conversion_count: 0,
    engagement_metrics: { likes: 3, comments: 2, shares: 0 },
    created_at: new Date("2023-10-14T11:30:00Z"),
    updated_at: new Date("2023-10-14T11:30:00Z"),
    customer_profile: {
      id: "c5",
      workspace_id: "workspace_1",
      name: "Alex Rivera",
      avatar_url: "https://randomuser.me/api/portraits/men/33.jpg",
      social_profiles: { username: "arivera", platform: "twitter" },
      created_at: new Date("2023-10-14T11:30:00Z"),
      updated_at: new Date("2023-10-14T11:30:00Z"),
    },
    source_data: {
      platform: "twitter",
      source: "mentions",
      sentiment: "negative",
      score: 0.23,
    },
    custom_fields: {},
  },
  {
    id: "t6",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "requested",
    content:
      "Just received my order from @brandname and I'm absolutely loving it! The quality is amazing and it looks even better in person. Will definitely be ordering more! #CustomerForLife",
    media_urls: [
      "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
      "https://images.unsplash.com/photo-1611162618479-ee4a37f6d4ad?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    ],
    collection_method: "social_import",
    verification_status: "unverified",
    published: false,
    tags: ["quality", "product", "appearance"],
    view_count: 0,
    share_count: 0,
    conversion_count: 0,
    engagement_metrics: { likes: 204, comments: 23 },
    created_at: new Date("2023-10-10T18:20:00Z"),
    updated_at: new Date("2023-10-10T18:20:00Z"),
    customer_profile: {
      id: "c6",
      workspace_id: "workspace_1",
      name: "Jamie Wilson",
      avatar_url: "https://randomuser.me/api/portraits/women/44.jpg",
      social_profiles: {
        username: "jamiewilson",
        platform: "instagram",
        followers: 1245,
      },
      created_at: new Date("2023-10-10T18:20:00Z"),
      updated_at: new Date("2023-10-10T18:20:00Z"),
    },
    source_data: {
      platform: "instagram",
      source: "tags",
      sentiment: "positive",
      score: 0.89,
    },
    custom_fields: {
      response:
        "Thank you for your wonderful feedback! We'd love to feature your testimonial on our website. Would that be okay with you?",
    },
  },
  {
    id: "t7",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "pending",
    content:
      "Just switched to @brandname and wish I'd done it sooner! Their customer support team went above and beyond to help with my migration. This is how you build customer loyalty! 🙌",
    collection_method: "social_import",
    verification_status: "unverified",
    published: false,
    tags: ["customer support", "migration", "loyalty"],
    view_count: 0,
    share_count: 8,
    conversion_count: 0,
    engagement_metrics: { likes: 42, comments: 6, shares: 8 },
    created_at: new Date("2023-10-17T08:45:00Z"),
    updated_at: new Date("2023-10-17T08:45:00Z"),
    customer_profile: {
      id: "c7",
      workspace_id: "workspace_1",
      name: "Taylor Nelson",
      avatar_url: "https://randomuser.me/api/portraits/women/66.jpg",
      social_profiles: {
        username: "tnelson",
        platform: "twitter",
        verified: false,
        followers: 987,
      },
      created_at: new Date("2023-10-17T08:45:00Z"),
      updated_at: new Date("2023-10-17T08:45:00Z"),
    },
    source_data: {
      platform: "twitter",
      source: "mentions",
      sentiment: "positive",
      score: 0.95,
    },
    custom_fields: {},
  },
  {
    id: "t8",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "pending",
    content:
      "I've been using the product for 2 weeks now. It's okay, but nothing revolutionary. There are some nice features, but also a few annoying bugs that should have been caught before release.",
    collection_method: "social_import",
    verification_status: "unverified",
    published: false,
    tags: ["bugs", "features", "medium satisfaction"],
    view_count: 0,
    share_count: 0,
    conversion_count: 0,
    engagement_metrics: { likes: 5, comments: 3 },
    created_at: new Date("2023-10-09T13:15:00Z"),
    updated_at: new Date("2023-10-09T13:15:00Z"),
    customer_profile: {
      id: "c8",
      workspace_id: "workspace_1",
      name: "David Chen",
      avatar_url: "https://randomuser.me/api/portraits/men/77.jpg",
      social_profiles: { username: "davidc", platform: "facebook" },
      created_at: new Date("2023-10-09T13:15:00Z"),
      updated_at: new Date("2023-10-09T13:15:00Z"),
    },
    source_data: {
      platform: "facebook",
      source: "comments",
      sentiment: "neutral",
      score: 0.51,
    },
    custom_fields: {},
  },
  {
    id: "t9",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "pending",
    content:
      "Our entire marketing team made the switch to @brandname last quarter, and we've seen a 30% increase in productivity. The collaboration features are unmatched in the industry. A game-changer for enterprise teams.",
    collection_method: "social_import",
    verification_status: "unverified",
    published: false,
    tags: ["enterprise", "marketing", "collaboration", "productivity"],
    view_count: 0,
    share_count: 27,
    conversion_count: 0,
    engagement_metrics: { likes: 211, comments: 34, shares: 27 },
    created_at: new Date("2023-10-16T15:10:00Z"),
    updated_at: new Date("2023-10-16T15:10:00Z"),
    customer_profile: {
      id: "c9",
      workspace_id: "workspace_1",
      name: "Rachel Kim",
      avatar_url: "https://randomuser.me/api/portraits/women/88.jpg",
      social_profiles: {
        username: "rachelkim",
        platform: "linkedin",
        verified: true,
        followers: 3458,
      },
      created_at: new Date("2023-10-16T15:10:00Z"),
      updated_at: new Date("2023-10-16T15:10:00Z"),
    },
    source_data: {
      platform: "linkedin",
      source: "posts",
      sentiment: "positive",
      score: 0.97,
    },
    custom_fields: { highlighted: true },
  },
  {
    id: "t10",
    workspace_id: "workspace_1",
    testimonial_type: "customer",
    format: "social_post",
    status: "approved",
    content:
      "Been trying out @brandname's new fitness tracking features and they are incredible! The integration with my other apps is seamless. This is how technology should work! #FitnessJourney",
    media_urls: [
      "https://images.unsplash.com/photo-1611162616475-46b635cb6d00?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    ],
    collection_method: "social_import",
    verification_status: "unverified",
    published: true,
    tags: ["fitness", "integration", "technology"],
    view_count: 0,
    share_count: 0,
    conversion_count: 0,
    engagement_metrics: { likes: 892, comments: 75 },
    created_at: new Date("2023-10-11T11:25:00Z"),
    updated_at: new Date("2023-10-11T11:25:00Z"),
    customer_profile: {
      id: "c10",
      workspace_id: "workspace_1",
      name: "Marcus Johnson",
      avatar_url: "https://randomuser.me/api/portraits/men/99.jpg",
      social_profiles: {
        username: "marcusjfit",
        platform: "instagram",
        followers: 15320,
      },
      created_at: new Date("2023-10-11T11:25:00Z"),
      updated_at: new Date("2023-10-11T11:25:00Z"),
    },
    source_data: {
      platform: "instagram",
      source: "tags",
      sentiment: "positive",
      score: 0.88,
    },
    custom_fields: {},
  },
];

export // Discovery mode info
const discoveryModes = [
  {
    id: "auto" as DiscoveryMode,
    name: "Auto Approval",
    description:
      "Automatically approve positive testimonials based on sentiment",
    icon: Zap,
    color: "text-green-600",
    bgColor: "bg-green-100",
  },
  {
    id: "manual" as DiscoveryMode,
    name: "Manual Review",
    description: "Manually review and approve all testimonials",
    icon: User,
    color: "text-blue-600",
    bgColor: "bg-blue-100",
  },
  {
    id: "keyword" as DiscoveryMode,
    name: "Keyword Based",
    description: "Approve testimonials containing specific keywords",
    icon: Search,
    color: "text-purple-600",
    bgColor: "bg-purple-100",
  },
  {
    id: "sentiment" as DiscoveryMode,
    name: "Sentiment Analysis",
    description: "Approve based on sentiment score thresholds",
    icon: Heart,
    color: "text-amber-600",
    bgColor: "bg-amber-100",
  },
  {
    id: "ai" as DiscoveryMode,
    name: "AI Powered",
    description: "Use AI to identify the best quality testimonials",
    icon: Sparkles,
    color: "text-indigo-600",
    bgColor: "bg-indigo-100",
  },
];
