# .github/workflows/backend.yml
name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "api-server/**"
      - ".github/workflows/api-server.yml"

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run Tests
        working-directory: ./backend
        run: go test ./...

      - name: Configure Oracle Cloud CLI
        uses: oracle-actions/configure-oci-credentials@v1
        with:
          fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          private-key: ${{ secrets.OCI_PRIVATE_KEY }}
          tenancy: ${{ secrets.OCI_TENANCY }}
          user: ${{ secrets.OCI_USER }}
          region: ${{ secrets.OCI_REGION }}

      - name: Build and Push Docker image
        working-directory: ./backend
        run: |
          docker build -t backend-api .
          docker tag backend-api ${{ secrets.OCI_REGISTRY }}/backend-api:${{ github.sha }}
          docker push ${{ secrets.OCI_REGISTRY }}/backend-api:${{ github.sha }}

      - name: Deploy to Oracle Cloud
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.BACKEND_HOST }} \
          "docker pull ${{ secrets.OCI_REGISTRY }}/backend-api:${{ github.sha }} && \
           docker stop backend-api || true && \
           docker rm backend-api || true && \
           docker run -d --name backend-api -p 8080:8080 \
           -e AI_SERVICE_HOST=${{ secrets.AI_SERVICE_HOST }} \
           -e AI_SERVICE_PORT=${{ secrets.AI_SERVICE_PORT }} \
           ${{ secrets.OCI_REGISTRY }}/backend-api:${{ github.sha }}"
