name: CI/CD Deploy

on:
  push:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: ifeanyidike
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: cenphidb_test
        options: >-
          --health-cmd "pg_isready -U ifeanyidike" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    strategy:
      matrix:
        service: [api-server, ai-service]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add caching here, right after checkout
      - name: Cache Go modules
        if: ${{ matrix.service == 'api-server' }}
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Python packages
        if: ${{ matrix.service == 'ai-service' }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create .env.test file
        run: |
          cat <<EOF > .env.test
          DB_USERNAME=ifeanyidike
          DB_PASSWORD=test_password
          DB_HOST=127.0.0.1
          DB_PORT=5434
          DB_NAME=cenphidb_test
          EOF

      # Optionally wait for the DB to be ready (using sleep or a health check)
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 5434; then
              echo "Postgres is up!"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done
          echo "Postgres did not start in time."
          exit 1

      # API Server tests (Golang)
      - name: Set up Go for API Server
        if: ${{ matrix.service == 'api-server' }}
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"
      - name: Test API Server
        if: ${{ matrix.service == 'api-server' }}
        run: |
          cd api-server
          go test ./...

      # AI Service tests (Python)
      - name: Set up Python for AI Service
        if: ${{ matrix.service == 'ai-service' }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies for AI Service
        if: ${{ matrix.service == 'ai-service' }}
        run: |
          cd ai-service
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Test AI Service
        if: ${{ matrix.service == 'ai-service' }}
        run: |
          cd ai-service
          python -m pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-server, ai-service]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add caching here, immediately after checkout
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-

      # Create necessary .env files for each service
      - name: Create .env files
        run: |
          if [ "${{ matrix.service }}" == "api-server" ]; then
            cat <<EOF > ./api-server/.env
            DB_USERNAME=ifeanyidike
            DB_PASSWORD=test_password
            DB_HOST=cenphidb
            DB_PORT=5432
            DB_NAME=cenphidb
            # Add other necessary API server variables
            EOF
          fi

          if [ "${{ matrix.service }}" == "ai-service" ]; then
            cat <<EOF > ./ai-service/.env
            # Add necessary AI service variables here
            PYTHONUNBUFFERED=1
            TRANSFORMERS_CACHE=/root/.cache/huggingface
            # Add other necessary AI service variables
            EOF
          fi

      # Install Docker Slim (Now known as Slim Toolkit)
      - name: Install Docker Slim
        run: |
          curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -
          slim --version

      # Set up Docker Buildx (for multi-platform builds if needed)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub with explicit settings
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false

      # Verify Docker login status
      - name: Verify Docker login
        run: |
          echo "Checking Docker login status..."
          docker info

      # Build and push with more explicit options
      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: lorddickson/${{ matrix.service }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        #   no-cache: false
        #   build-args: |
        #     BUILDKIT_INLINE_CACHE=1

      # For the AI service, run your slim process
      - name: Slim AI Service Image
        if: ${{ matrix.service == 'ai-service' }}
        working-directory: ai-service
        run: |
          # Make sure the image exists before trying to slim it
          docker pull lorddickson/ai-service:latest || { echo "Failed to pull image, cannot slim"; exit 1; }
          make slim-docker-full IMAGE_NAME=lorddickson/ai-service:latest

          # Push the slimmed image if slimming was successful
          if [ $? -eq 0 ]; then
            docker push lorddickson/ai-service.slim:latest
          else
            echo "Slimming failed, using original image"
          fi

  deploy_api:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH Deploy to API Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.API_SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/opc
            # Pull the latest images
            docker pull lorddickson/api-server:latest
            # Run deploy script
            ./deploy.sh

  deploy_ai:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH Deploy to AI Service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AI_SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/opc
            # Pull the latest images
            docker pull lorddickson/ai-service:latest
            # Try to pull slim image if it exists
            docker pull lorddickson/ai-service.slim:latest || echo "Slim image not found, will use regular image"
            # Run deploy script
            ./deploy.sh
